ContaAzul/creditcard.js

README.md

Improved the lettering a little bit, so it looks nicer.
Also improved the `sh` examples, adding syntax and the preceding `$`.

Improved english in README

---

.banner
bower.json

In order to publish the [Bower](http://bower.io/), this commit change the author name and remove `private` attribute from `bower.json`.
@ContaAzul/domphysis

Change author and make public on bower.json

---

README.md
package.json

- Remove CDN information;
- Add link to zip file;
- Fix param on `require()` example.

Fix README, main file and bump version

---

.gitignore
dist/browser/creditcard.js
dist/browser/creditcard.min.js
package.json

- Remove rimraf
- Remove `clean` task.
- Bump version.

Change build workflow.

---

index.html

Improving wording and the like.

English improvements

---

index.html

refs #15 
* Atualização dos nomes das funções. 
* Adicionado `Checked` no safari e IE. 
@fernahh 
@matheuspoleza 
@ContaAzul/domphysis

Correções no index 

---

LICENSE.md
bower.json
dist/creditcard.js
dist/creditcard.min.js
package.json

- Changed release tag version
- Create LICENSE file

adding first release tag

---

index.html

The size of the column was incorrect
Before:
After:
@fernahh

column length correction

---

README.md

Its not a dev library. The readme was like <code>npm install --save-dev creditcard.js</code>. I change to <code>npm install --save creditcard.js</code>

Update README npm install

---

index.html

Updated creditcard.js site according to #25

Update npm install helper

---

README.md

There is no space between the words.

Fix company name

---

package-lock.json
package.json

fix: bump moment

---

dist/creditcard.js
dist/creditcard.min.js
package-lock.json
package.json

We found a potential security vulnerability in one of your dependencies.

Update dev dependencies

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Adiciona um template para criação de issues e PR`s ao projeto. 
Isso vai facilitar melhor descrição de ambas as coisas.

Added templates to create pullrequest and issues

---

src/creditcard.js
src/creditcard.test.js

Remove mutables values 

---

.github/workflows/ci.yml
.travis.yml

Changing config os Github Actions to using scripts of new V3

Configure Github Actions on V3

---

.github/workflows/ci.yml
src/creditcard.test.js

Add 100% coverage check to Github Actions

Add coverage to Actions

---

src/cards.js
src/creditcard.test.js

Add JCB Card to available validations

Add JCB Card

---

package.json
rollup.config.js
yarn.lock

- Add lib `rollup-plugin-terser`
- Add config to build a uglified package version

Add uglified package version

---

README.md

docs: add npm badge

---

package.json

fix: installation on other package managers

---

README.md

chore: add credits

---

.github/workflows/deploy-npm.yml

Created environment varibales for author and email.
The Aikido vulberability: https://app.aikido.dev/repositories/613757
N/A
* [AZUL-63636](https://contaazul.atlassian.net/browse/AZUL-63636)
[AZUL-63636]: https://contaazul.atlassian.net/browse/AZUL-63636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AZUL-63636 | feat: fix vulnerability

---

.github/workflows/deploy-npm.yml

Change `actions/cache` from v2 to v4.
v2 is deprecated.
N/A

AZUL-63636 | Cross/feat/azul 63636 vulnerabilities
